function envsetup()
    cd(fileparts(which(mfilename)));
    addpath('./libs');

    Simulink.fileGenControl('set', ...
        'CacheFolder'  , fullfile(pwd,'cache/cache'), ...
        'CodeGenFolder', fullfile(pwd,'cache/codegen'), ...
        'CodeGenFolderStructure', Simulink.filegen.CodeGenFolderStructure.TargetEnvironmentSubfolder, ...
        'createDir',true);
end