webtalk_init -webtalk_dir D:/Vivado/Projects/Verilog/Complex_multiplyer/ComplexMulty/ComplexMulty.sim/sim_1/behav/xsim.dir/Multiplayer_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 17 22:47:46 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "aeb3740f-f012-4cd2-b28b-798d6b14332e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f2921417f3f24de39ae28993a8b11788" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8216_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2977390721 -regid "" -xml D:/Vivado/Projects/Verilog/Complex_multiplyer/ComplexMulty/ComplexMulty.sim/sim_1/behav/xsim.dir/Multiplayer_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Vivado/Projects/Verilog/Complex_multiplyer/ComplexMulty/ComplexMulty.sim/sim_1/behav/xsim.dir/Multiplayer_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Vivado/Projects/Verilog/Complex_multiplyer/ComplexMulty/ComplexMulty.sim/sim_1/behav/xsim.dir/Multiplayer_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
