######################################################################
#
# File name : tb_complex_mult_compile.do
# Created on: Sat Jun 10 09:26:21 +0300 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\ModuleSim\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
C:\\ModuleSim\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

C:\\ModuleSim\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\ModuleSim\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\ModuleSim\\modeltech64_2020.4\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../../25.04.23/rtl/complex_mult.v" \

C:\\ModuleSim\\modeltech64_2020.4\\win64\\vlog  -incr -mfcu -sv -work xil_defaultlib  \
"../../../../../25.04.23/rtl/tb_complex_mult.sv" \


# compile glbl module
C:\\ModuleSim\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

