######################################################################
#
# File name : tb_complex_mult_simulate.do
# Created on: Sat Jun 10 09:26:25 +0300 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_complex_mult xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_complex_mult_wave.do}

view wave
view structure
view signals

do {tb_complex_mult.udo}

run 1000ns
