######################################################################
#
# File name : tb_complex_mult_wave.do
# Created on: Tue Jun 06 04:30:01 +0300 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
