# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xczu3eg-sfvc784-2L-e-EVAL

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado/Projects/Verilog/Complex_multiplyer/ComplexMulty/ComplexMulty.cache/wt [current_project]
set_property parent.project_path D:/Vivado/Projects/Verilog/Complex_multiplyer/ComplexMulty/ComplexMulty.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado/Projects/Verilog/Complex_multiplyer/ComplexMulty/ComplexMulty.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Vivado/Projects/Verilog/Complex_multiplyer/complex_mult.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top complex_mult -part xczu3eg-sfvc784-2L-e-EVAL


write_checkpoint -force -noxdef complex_mult.dcp

catch { report_utilization -file complex_mult_utilization_synth.rpt -pb complex_mult_utilization_synth.pb }
